### ISSUE TITLE
nevermind

### ISSUE THREAD

**Issue by andrw-zh** [mrmillerforcs/TreasureHunterV1#1]

**Comment by mrmillerforcs** [comment]
I KNOW RIGHT?!!  That's a huge bug, but one that i was going to have teams solve as part of the activity. Although i really hate it; you want to try and fix it for me? 🙂
________________________________
From: Andrew Zhang ***@***.***>
Sent: Wednesday, December 13, 2023 10:51 PM
To: mrmillerforcs/TreasureHunterV1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mrmillerforcs/TreasureHunterV1] code will fail to move hunter to new biome if they buy an item and typed all lowercase! (Issue #1)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

very bad!!

**Comment by andrw-zh** [comment]
I thought it was an intended bug, so I thought "nevermind, Miller must've done it on purpose"! I think I already figured out what the issue is and I can fix it.

**Comment by mrmillerforcs** [comment]
it wasn't done on purpose, but i kept the bug as something that needed fixing (because i was too lazy to fix it on my own) -- but's it's really annoying at the start, so it's worth fixing now.  want to handle it? :)

**Comment by andrw-zh** [comment]
hi quick question!!!
Can I make the scanner object static and final? It shouldn't have to be modified and objects shouldn't need to create a new scanner object every time it is instantiated.

**Comment by mrmillerforcs** [comment]
excellent suggestion and please do!  if there are any other code clean-up things you want to do, please feel free

p.s. i am going to share your updated version of the program with the class tomorrow :p
